Symbols = {'3MINDIA': '3M India Ltd.',
    'ABB': 'ABB India Ltd.',
    'ACC': 'ACC Ltd.',
    'AIAENG': 'AIA Engineering Ltd.',
    'APLAPOLLO': 'APL Apollo Tubes Ltd.',
    'AUBANK': 'AU Small Finance Bank Ltd.',
    'AARTIDRUGS': 'Aarti Drugs Ltd.',
    'AARTIIND': 'Aarti Industries Ltd.',
    'AAVAS': 'Aavas Financiers Ltd.',
    'ABBOTINDIA': 'Abbott India Ltd.',
    'ADANIENT': 'Adani Enterprises Ltd.',
    'ADANIGREEN': 'Adani Green Energy Ltd.',
    'ADANIPORTS': 'Adani Ports and Special Economic Zone Ltd.',
    'ATGL': 'Adani Total Gas Ltd.',
    'ADANITRANS': 'Adani Transmission Ltd.',
    'ABCAPITAL': 'Aditya Birla Capital Ltd.',
    'ABFRL': 'Aditya Birla Fashion and Retail Ltd.',
    'ABSLAMC': 'Aditya Birla Sun Life AMC Ltd.',
    'ADVENZYMES': 'Advanced Enzyme Tech Ltd.',
    'AEGISCHEM': 'Aegis Logistics Ltd.',
    'AFFLE': 'Affle (India) Ltd.',
    'AJANTPHARM': 'Ajanta Pharmaceuticals Ltd.',
    'APLLTD': 'Alembic Pharmaceuticals Ltd.',
    'ALKEM': 'Alkem Laboratories Ltd.',
    'ALKYLAMINE': 'Alkyl Amines Chemicals Ltd.',
    'ALLCARGO': 'Allcargo Logistics Ltd.',
    'ALOKINDS': 'Alok Industries Ltd.',
    'AMARAJABAT': 'Amara Raja Batteries Ltd.',
    'AMBER': 'Amber Enterprises India Ltd.',
    'AMBUJACEM': 'Ambuja Cements Ltd.',
    'ANGELONE': 'Angel One Ltd.',
    'ANURAS': 'Anupam Rasayan India Ltd.',
    'APOLLOHOSP': 'Apollo Hospitals Enterprise Ltd.',
    'APOLLOTYRE': 'Apollo Tyres Ltd.',
    'APTUS': 'Aptus Value Housing Finance India Ltd.',
    'ASAHIINDIA': 'Asahi India Glass Ltd.',
    'ASHOKLEY': 'Ashok Leyland Ltd.',
    'ASTERDM': 'Aster DM Healthcare Ltd.',
    'ASTRAZEN': 'AstraZenca Pharma India Ltd.',
    'ASTRAL': 'Astral Ltd.',
    'ATUL': 'Atul Ltd.',
    'AUROPHARMA': 'Aurobindo Pharma Ltd.',
    'AVANTIFEED': 'Avanti Feeds Ltd.',
    'DMART': 'Avenue Supermarts Ltd.',
    'AXISBANK': 'Axis Bank Ltd.',
    'BASF': 'BASF India Ltd.',
    'BSE': 'BSE Ltd.',
    'BAJAJ-AUTO': 'Bajaj Auto Ltd.',
    'BAJAJELEC': 'Bajaj Electricals Ltd',
    'BAJFINANCE': 'Bajaj Finance Ltd.',
    'BAJAJFINSV': 'Bajaj Finserv Ltd.',
    'BAJAJHLDNG': 'Bajaj Holdings & Investment Ltd.',
    'BALAMINES': 'Balaji Amines Ltd.',
    'BALKRISIND': 'Balkrishna Industries Ltd.',
    'BALRAMCHIN': 'Balrampur Chini Mills Ltd.',
    'BANDHANBNK': 'Bandhan Bank Ltd.',
    'BANKBARODA': 'Bank of Baroda',
    'BANKINDIA': 'Bank of India',
    'MAHABANK': 'Bank of Maharashtra',
    'BATAINDIA': 'Bata India Ltd.',
    'BAYERCROP': 'Bayer Cropscience Ltd.',
    'BERGEPAINT': 'Berger Paints India Ltd.',
    'BDL': 'Bharat Dynamics Ltd.',
    'BEL': 'Bharat Electronics Ltd.',
    'BHARATFORG': 'Bharat Forge Ltd.',
    'BHEL': 'Bharat Heavy Electricals Ltd.',
    'BPCL': 'Bharat Petroleum Corporation Ltd.',
    'BHARTIARTL': 'Bharti Airtel Ltd.',
    'BIOCON': 'Biocon Ltd.',
    'BIRLACORPN': 'Birla Corporation Ltd.',
    'BSOFT': 'Birlasoft Ltd.',
    'BLUEDART': 'Blue Dart Express Ltd.',
    'BLUESTARCO': 'Blue Star Ltd.',
    'BBTC': 'Bombay Burmah Trading Corporation Ltd.',
    'BORORENEW': 'Borosil Renewables Ltd.',
    'BOSCHLTD': 'Bosch Ltd.',
    'BRIGADE': 'Brigade Enterprises Ltd.',
    'BCG': 'Brightcom Group Ltd.',
    'BRITANNIA': 'Britannia Industries Ltd.',
    'MAPMYINDIA': 'C.E. Info Systems Ltd.',
    'CCL': 'CCL Products (I) Ltd.',
    'CESC': 'CESC Ltd.',
    'CGPOWER': 'CG Power and Industrial Solutions Ltd.',
    'CRISIL': 'CRISIL Ltd.',
    'CSBBANK': 'CSB Bank Ltd.',
    'CANFINHOME': 'Can Fin Homes Ltd.',
    'CANBK': 'Canara Bank',
    'CAPLIPOINT': 'Caplin Point Laboratories Ltd.',
    'CGCL': 'Capri Global Capital Ltd.',
    'CARBORUNIV': 'Carborundum Universal Ltd.',
    'CASTROLIND': 'Castrol India Ltd.',
    'CEATLTD': 'Ceat Ltd.',
    'CENTRALBK': 'Central Bank of India',
    'CDSL': 'Central Depository Services (India) Ltd.',
    'CENTURYPLY': 'Century Plyboards (India) Ltd.',
    'CENTURYTEX': 'Century Textile & Industries Ltd.',
    'CERA': 'Cera Sanitaryware Ltd',
    'CHALET': 'Chalet Hotels Ltd.',
    'CHAMBLFERT': 'Chambal Fertilizers & Chemicals Ltd.',
    'CHEMPLASTS': 'Chemplast Sanmar Ltd.',
    'CHOLAHLDNG': 'Cholamandalam Financial Holdings Ltd.',
    'CHOLAFIN': 'Cholamandalam Investment and Finance Company Ltd.',
    'CIPLA': 'Cipla Ltd.',
    'CUB': 'City Union Bank Ltd.',
    'CLEAN': 'Clean Science and Technology Ltd.',
    'COALINDIA': 'Coal India Ltd.',
    'COCHINSHIP': 'Cochin Shipyard Ltd.',
    'COFORGE': 'Coforge Ltd.',
    'COLPAL': 'Colgate Palmolive (India) Ltd.',
    'CAMS': 'Computer Age Management Services Ltd.',
    'CONCOR': 'Container Corporation of India Ltd.',
    'COROMANDEL': 'Coromandel International Ltd.',
    'CREDITACC': 'CreditAccess Grameen Ltd.',
    'CROMPTON': 'Crompton Greaves Consumer Electricals Ltd.',
    'CUMMINSIND': 'Cummins India Ltd.',
    'CYIENT': 'Cyient Ltd.',
    'DCMSHRIRAM': 'DCM Shriram Ltd.',
    'DLF': 'DLF Ltd.',
    'DABUR': 'Dabur India Ltd.',
    'DALBHARAT': 'Dalmia Bharat Ltd.',
    'DEEPAKNTR': 'Deepak Nitrite Ltd.',
    'DELTACORP': 'Delta Corp Ltd.',
    'DEVYANI': 'Devyani International Ltd.',
    'DHANI': 'Dhani Services Ltd.',
    'DBL': 'Dilip Buildcon Ltd.',
    'DIVISLAB': "Divi's Laboratories Ltd.",
    'DIXON': 'Dixon Technologies (India) Ltd.',
    'LALPATHLAB': 'Dr. Lal Path Labs Ltd.',
    'DRREDDY': "Dr. Reddy's Laboratories Ltd.",
    'EIDPARRY': 'E.I.D. Parry (India) Ltd.',
    'EIHOTEL': 'EIH Ltd.',
    'EPL': 'EPL Ltd.',
    'EASEMYTRIP': 'Easy Trip Planners Ltd.',
    'EDELWEISS': 'Edelweiss Financial Services Ltd.',
    'EICHERMOT': 'Eicher Motors Ltd.',
    'ELGIEQUIP': 'Elgi Equipments Ltd.',
    'EMAMILTD': 'Emami Ltd.',
    'ENDURANCE': 'Endurance Technologies Ltd.',
    'ENGINERSIN': 'Engineers India Ltd.',
    'EQUITAS': 'Equitas Holdings Ltd.',
    'EQUITASBNK': 'Equitas Small Finance Bank Ltd.',
    'ERIS': 'Eris Lifesciences Ltd.',
    'ESCORTS': 'Escorts Ltd.',
    'EXIDEIND': 'Exide Industries Ltd.',
    'FDC': 'FDC Ltd.',
    'NYKAA': 'FSN E-Commerce Ventures Ltd.',
    'FEDERALBNK': 'Federal Bank Ltd.',
    'FACT': 'Fertilisers and Chemicals Travancore Ltd.',
    'FINEORG': 'Fine Organic Industries Ltd.',
    'FINCABLES': 'Finolex Cables Ltd.',
    'FINPIPE': 'Finolex Industries Ltd.',
    'FSL': 'Firstsource Solutions Ltd.',
    'FORTIS': 'Fortis Healthcare Ltd.',
    'GRINFRA': 'G R Infraprojects Ltd.',
    'GAIL': 'GAIL (India) Ltd.',
    'GMMPFAUDLR': 'GMM Pfaudler Ltd.',
    'GALAXYSURF': 'Galaxy Surfactants Ltd.',
    'GARFIBRES': 'Garware Technical Fibres Ltd.',
    'GICRE': 'General Insurance Corporation of India',
    'GLAND': 'Gland Pharma Ltd.',
    'GLAXO': 'Glaxosmithkline Pharmaceuticals Ltd.',
    'GLS': 'Glenmark Life Sciences Ltd.',
    'GLENMARK': 'Glenmark Pharmaceuticals Ltd.',
    'GOCOLORS': 'Go Fashion (India) Ltd.',
    'GODFRYPHLP': 'Godfrey Phillips India Ltd.',
    'GODREJAGRO': 'Godrej Agrovet Ltd.',
    'GODREJCP': 'Godrej Consumer Products Ltd.',
    'GODREJIND': 'Godrej Industries Ltd.',
    'GODREJPROP': 'Godrej Properties Ltd.',
    'GRANULES': 'Granules India Ltd.',
    'GRAPHITE': 'Graphite India Ltd.',
    'GRASIM': 'Grasim Industries Ltd.',
    'GESHIP': 'Great Eastern Shipping Co. Ltd.',
    'GRINDWELL': 'Grindwell Norton Ltd.',
    'GUJALKALI': 'Gujarat Alkalies & Chemicals Ltd.',
    'GAEL': 'Gujarat Ambuja Exports Ltd.',
    'FLUOROCHEM': 'Gujarat Fluorochemicals Ltd.',
    'GUJGASLTD': 'Gujarat Gas Ltd.',
    'GNFC': 'Gujarat Narmada Valley Fertilizers and Chemicals Ltd.',
    'GPPL': 'Gujarat Pipavav Port Ltd.',
    'GSFC': 'Gujarat State Fertilizers & Chemicals Ltd.',
    'GSPL': 'Gujarat State Petronet Ltd.',
    'HEG': 'H.E.G. Ltd.',
    'HCLTECH': 'HCL Technologies Ltd.',
    'HDFCAMC': 'HDFC Asset Management Company Ltd.',
    'HDFCBANK': 'HDFC Bank Ltd.',
    'HDFCLIFE': 'HDFC Life Insurance Company Ltd.',
    'HFCL': 'HFCL Ltd.',
    'HLEGLAS': 'HLE Glascoat Ltd.',
    'HAPPSTMNDS': 'Happiest Minds Technologies Ltd.',
    'HATHWAY': 'Hathway Cable & Datacom Ltd.',
    'HATSUN': 'Hatsun Agro Product Ltd.',
    'HAVELLS': 'Havells India Ltd.',
    'HEMIPROP': 'Hemisphere Properties India Ltd.',
    'HEROMOTOCO': 'Hero MotoCorp Ltd.',
    'HIKAL': 'Hikal Ltd.',
    'HINDALCO': 'Hindalco Industries Ltd.',
    'HGS': 'Hinduja Global Solutions Ltd.',
    'HAL': 'Hindustan Aeronautics Ltd.',
    'HINDCOPPER': 'Hindustan Copper Ltd.',
    'HINDPETRO': 'Hindustan Petroleum Corporation Ltd.',
    'HINDUNILVR': 'Hindustan Unilever Ltd.',
    'HINDZINC': 'Hindustan Zinc Ltd.',
    'POWERINDIA': 'Hitachi Energy India Ltd.',
    'HOMEFIRST': 'Home First Finance Company India Ltd.',
    'HONAUT': 'Honeywell Automation India Ltd.',
    'HUDCO': 'Housing & Urban Development Corporation Ltd.',
    'HDFC': 'Housing Development Finance Corporation Ltd.',
    'ICICIBANK': 'ICICI Bank Ltd.',
    'ICICIGI': 'ICICI Lombard General Insurance Company Ltd.',
    'ICICIPRULI': 'ICICI Prudential Life Insurance Company Ltd.',
    'ISEC': 'ICICI Securities Ltd.',
    'IDBI': 'IDBI Bank Ltd.',
    'IDFCFIRSTB': 'IDFC First Bank Ltd.',
    'IDFC': 'IDFC Ltd.',
    'IFBIND': 'IFB Industries Ltd.',
    'IIFL': 'IIFL Finance Ltd.',
    'IIFLWAM': 'IIFL Wealth Management Ltd.',
    'IRB': 'IRB Infrastructure Developers Ltd.',
    'IRCON': 'IRCON International Ltd.',
    'ITC': 'ITC Ltd.',
    'ITI': 'ITI Ltd.',
    'INDIACEM': 'India Cements Ltd.',
    'IBULHSGFIN': 'Indiabulls Housing Finance Ltd.',
    'IBREALEST': 'Indiabulls Real Estate Ltd.',
    'INDIAMART': 'Indiamart Intermesh Ltd.',
    'INDIANB': 'Indian Bank',
    'IEX': 'Indian Energy Exchange Ltd.',
    'INDHOTEL': 'Indian Hotels Co. Ltd.',
    'IOC': 'Indian Oil Corporation Ltd.',
    'IOB': 'Indian Overseas Bank',
    'IRCTC': 'Indian Railway Catering And Tourism Corporation Ltd.',
    'IRFC': 'Indian Railway Finance Corporation Ltd.',
    'INDIGOPNTS': 'Indigo Paints Ltd.',
    'ICIL': 'Indo Count Industries Ltd.',
    'INDOCO': 'Indoco Remedies Ltd.',
    'IGL': 'Indraprastha Gas Ltd.',
    'INDUSTOWER': 'Indus Towers Ltd.',
    'INDUSINDBK': 'IndusInd Bank Ltd.',
    'INFIBEAM': 'Infibeam Avenues Ltd.',
    'NAUKRI': 'Info Edge (India) Ltd.',
    'INFY': 'Infosys Ltd.',
    'INOXLEISUR': 'Inox Leisure Ltd.',
    'INTELLECT': 'Intellect Design Arena Ltd.',
    'INDIGO': 'InterGlobe Aviation Ltd.',
    'IPCALAB': 'Ipca Laboratories Ltd.',
    'JBCHEPHARM': 'J.B. Chemicals & Pharmaceuticals Ltd.',
    'JKCEMENT': 'J.K. Cement Ltd.',
    'JKLAKSHMI': 'JK Lakshmi Cement Ltd.',
    'JKPAPER': 'JK Paper Ltd.',
    'JMFINANCIL': 'JM Financial Ltd.',
    'JSWENERGY': 'JSW Energy Ltd.',
    'JSWSTEEL': 'JSW Steel Ltd.',
    'JAMNAAUTO': 'Jamna Auto Industries Ltd.',
    'JSLHISAR': 'Jindal Stainless (Hisar) Ltd.',
    'JSL': 'Jindal Stainless Ltd.',
    'JINDALSTEL': 'Jindal Steel & Power Ltd.',
    'JUBLFOOD': 'Jubilant Foodworks Ltd.',
    'JUBLINGREA': 'Jubilant Ingrevia Ltd.',
    'JUBLPHARMA': 'Jubilant Pharmova Ltd.',
    'JUSTDIAL': 'Justdial Ltd.',
    'JYOTHYLAB': 'Jyothy Labs Ltd.',
    'KPRMILL': 'K.P.R. Mill Ltd.',
    'KEI': 'KEI Industries Ltd.',
    'KNRCON': 'KNR Constructions Ltd.',
    'KPITTECH': 'KPIT Technologies Ltd.',
    'KRBL': 'KRBL Ltd.',
    'KAJARIACER': 'Kajaria Ceramics Ltd.',
    'KALPATPOWR': 'Kalpataru Power Transmission Ltd.',
    'KALYANKJIL': 'Kalyan Jewellers India Ltd.',
    'KANSAINER': 'Kansai Nerolac Paints Ltd.',
    'KARURVYSYA': 'Karur Vysya Bank Ltd.',
    'KEC': 'Kec International Ltd.',
    'KOTAKBANK': 'Kotak Mahindra Bank Ltd.',
    'KIMS': 'Krishna Institute of Medical Sciences Ltd.',
    'L&TFH': 'L&T Finance Holdings Ltd.',
    'LTTS': 'L&T Technology Services Ltd.',
    'LICHSGFIN': 'LIC Housing Finance Ltd.',
    'LAXMIMACH': 'Lakshmi Machine Works Ltd.',
    'LTI': 'Larsen & Toubro Infotech Ltd.',
    'LT': 'Larsen & Toubro Ltd.',
    'LATENTVIEW': 'Latent View Analytics Ltd.',
    'LAURUSLABS': 'Laurus Labs Ltd.',
    'LXCHEM': 'Laxmi Organic Industries Ltd.',
    'LINDEINDIA': 'Linde India Ltd.',
    'LICI': 'Life Insurance Corporation of India',
    'LUPIN': 'Lupin Ltd.',
    'LUXIND': 'Lux Industries Ltd.',
    'MMTC': 'MMTC Ltd.',
    'MOIL': 'MOIL Ltd.',
    'MRF': 'MRF Ltd.',
    'MTARTECH': 'MTAR Technologies Ltd.',
    'LODHA': 'Macrotech Developers Ltd.',
    'MGL': 'Mahanagar Gas Ltd.',
    'M&MFIN': 'Mahindra & Mahindra Financial Services Ltd.',
    'M&M': 'Mahindra & Mahindra Ltd.',
    'MAHINDCIE': 'Mahindra CIE Automotive Ltd.',
    'MHRIL': 'Mahindra Holidays & Resorts India Ltd.',
    'MAHLOG': 'Mahindra Logistics Ltd.',
    'MANAPPURAM': 'Manappuram Finance Ltd.',
    'MRPL': 'Mangalore Refinery & Petrochemicals Ltd.',
    'MARICO': 'Marico Ltd.',
    'MARUTI': 'Maruti Suzuki India Ltd.',
    'MASTEK': 'Mastek Ltd.',
    'MFSL': 'Max Financial Services Ltd.',
    'MAXHEALTH': 'Max Healthcare Institute Ltd.',
    'MAZDOCK': 'Mazagoan Dock Shipbuilders Ltd.',
    'MEDPLUS': 'Medplus Health Services Ltd.',
    'METROBRAND': 'Metro Brands Ltd.',
    'METROPOLIS': 'Metropolis Healthcare Ltd.',
    'MINDTREE': 'MindTree Ltd.',
    'MINDAIND': 'Minda Industries Ltd.',
    'MOTILALOFS': 'Motilal Oswal Financial Services Ltd.',
    'MPHASIS': 'MphasiS Ltd.',
    'MCX': 'Multi Commodity Exchange of India Ltd.',
    'MUTHOOTFIN': 'Muthoot Finance Ltd.',
    'NATCOPHARM': 'NATCO Pharma Ltd.',
    'NBCC': 'NBCC (India) Ltd.',
    'NCC': 'NCC Ltd.',
    'NESCO': 'NESCO Ltd.',
    'NHPC': 'NHPC Ltd.',
    'NLCINDIA': 'NLC India Ltd.',
    'NMDC': 'NMDC Ltd.',
    'NOCIL': 'NOCIL Ltd.',
    'NTPC': 'NTPC Ltd.',
    'NH': 'Narayana Hrudayalaya Ltd.',
    'NATIONALUM': 'National Aluminium Co. Ltd.',
    'NAVINFLUOR': 'Navin Fluorine International Ltd.',
    'NAZARA': 'Nazara Technologies Ltd.',
    'NESTLEIND': 'Nestle India Ltd.',
    'NETWORK18': 'Network18 Media & Investments Ltd.',
    'NAM-INDIA': 'Nippon Life India Asset Management Ltd.',
    'NUVOCO': 'Nuvoco Vistas Corporation Ltd.',
    'OBEROIRLTY': 'Oberoi Realty Ltd.',
    'ONGC': 'Oil & Natural Gas Corporation Ltd.',
    'OIL': 'Oil India Ltd.',
    'PAYTM': 'One 97 Communications Ltd.',
    'OFSS': 'Oracle Financial Services Software Ltd.',
    'ORIENTELEC': 'Orient Electric Ltd.',
    'POLICYBZR': 'PB Fintech Ltd.',
    'PCBL': 'PCBL Ltd.',
    'PIIND': 'PI Industries Ltd.',
    'PNBHOUSING': 'PNB Housing Finance Ltd.',
    'PNCINFRA': 'PNC Infratech Ltd.',
    'PVR': 'PVR Ltd.',
    'PAGEIND': 'Page Industries Ltd.',
    'PERSISTENT': 'Persistent Systems Ltd.',
    'PETRONET': 'Petronet LNG Ltd.',
    'PFIZER': 'Pfizer Ltd.',
    'PHOENIXLTD': 'Phoenix Mills Ltd.',
    'PIDILITIND': 'Pidilite Industries Ltd.',
    'PEL': 'Piramal Enterprises Ltd.',
    'POLYMED': 'Poly Medicure Ltd.',
    'POLYCAB': 'Polycab India Ltd.',
    'POLYPLEX': 'Polyplex Corporation Ltd.',
    'POONAWALLA': 'Poonawalla Fincorp Ltd.',
    'PFC': 'Power Finance Corporation Ltd.',
    'POWERGRID': 'Power Grid Corporation of India Ltd.',
    'PRAJIND': 'Praj Industries Ltd.',
    'PRESTIGE': 'Prestige Estates Projects Ltd.',
    'PRINCEPIPE': 'Prince Pipes and Fittings Ltd.',
    'PRSMJOHNSN': 'Prism Johnson Ltd.',
    'PRIVISCL': 'Privi Speciality Chemicals Ltd.',
    'PGHL': 'Procter & Gamble Health Ltd.',
    'PGHH': 'Procter & Gamble Hygiene & Health Care Ltd.',
    'PNB': 'Punjab National Bank',
    'QUESS': 'Quess Corp Ltd.',
    'RBLBANK': 'RBL Bank Ltd.',
    'RECLTD': 'REC Ltd.',
    'RHIM': 'RHI MAGNESITA INDIA LTD.',
    'RITES': 'RITES Ltd.',
    'RADICO': 'Radico Khaitan Ltd',
    'RVNL': 'Rail Vikas Nigam Ltd.',
    'RAILTEL': 'Railtel Corporation Of India Ltd.',
    'RAIN': 'Rain Industries Ltd',
    'RAJESHEXPO': 'Rajesh Exports Ltd.',
    'RALLIS': 'Rallis India Ltd.',
    'RCF': 'Rashtriya Chemicals & Fertilizers Ltd.',
    'RATNAMANI': 'Ratnamani Metals & Tubes Ltd.',
    'RTNINDIA': 'RattanIndia Enterprises Ltd.',
    'REDINGTON': 'Redington (India) Ltd.',
    'RELAXO': 'Relaxo Footwears Ltd.',
    'RELIANCE': 'Reliance Industries Ltd.',
    'RBA': 'Restaurant Brands Asia Ltd.',
    'ROSSARI': 'Rossari Biotech Ltd.',
    'ROUTE': 'Route Mobile Ltd.',
    'SBICARD': 'SBI Cards and Payment Services Ltd.',
    'SBILIFE': 'SBI Life Insurance Company Ltd.',
    'SIS': 'SIS Ltd.',
    'SJVN': 'SJVN Ltd.',
    'SKFINDIA': 'SKF India Ltd.',
    'SRF': 'SRF Ltd.',
    'SANOFI': 'Sanofi India Ltd.',
    'SAPPHIRE': 'Sapphire Foods India Ltd.',
    'SAREGAMA': 'Saregama India Ltd',
    'SCHAEFFLER': 'Schaeffler India Ltd.',
    'SEQUENT': 'Sequent Scientific Ltd.',
    'SFL': 'Sheela Foam Ltd.',
    'SHILPAMED': 'Shilpa Medicare Ltd.',
    'SCI': 'Shipping Corporation of India Ltd.',
    'SHREECEM': 'Shree Cement Ltd.',
    'RENUKA': 'Shree Renuka Sugars Ltd.',
    'SHRIRAMCIT': 'Shriram City Union Finance Ltd.',
    'SRTRANSFIN': 'Shriram Transport Finance Co. Ltd.',
    'SHYAMMETL': 'Shyam Metalics and Energy Ltd.',
    'SIEMENS': 'Siemens Ltd.',
    'SOBHA': 'Sobha Ltd.',
    'SOLARINDS': 'Solar Industries India Ltd.',
    'SOLARA': 'Solara Active Pharma Sciences Ltd.',
    'SONACOMS': 'Sona BLW Precision Forgings Ltd.',
    'SONATSOFTW': 'Sonata Software Ltd.',
    'SPICEJET': 'Spicejet Ltd.',
    'STARHEALTH': 'Star Health and Allied Insurance Company Ltd.',
    'SBIN': 'State Bank of India',
    'SAIL': 'Steel Authority of India Ltd.',
    'SWSOLAR': 'Sterling and Wilson Renewable Energy Ltd.',
    'STLTECH': 'Sterlite Technologies Ltd.',
    'STAR': 'Strides Pharma Science Ltd.',
    'SUDARSCHEM': 'Sudarshan Chemical Industries Ltd.',
    'SUMICHEM': 'Sumitomo Chemical India Ltd.',
    'SPARC': 'Sun Pharma Advanced Research Company Ltd.',
    'SUNPHARMA': 'Sun Pharmaceutical Industries Ltd.',
    'SUNTV': 'Sun TV Network Ltd.',
    'SUNDARMFIN': 'Sundaram Finance Ltd.',
    'SUNDRMFAST': 'Sundram Fasteners Ltd.',
    'SUNTECK': 'Sunteck Realty Ltd.',
    'SUPRAJIT': 'Suprajit Engineering Ltd.',
    'SUPREMEIND': 'Supreme Industries Ltd.',
    'SUVENPHAR': 'Suven Pharmaceuticals Ltd.',
    'SUZLON': 'Suzlon Energy Ltd.',
    'SYMPHONY': 'Symphony Ltd.',
    'SYNGENE': 'Syngene International Ltd.',
    'TCIEXP': 'TCI Express Ltd.',
    'TCNSBRANDS': 'TCNS Clothing Co. Ltd.',
    'TTKPRESTIG': 'TTK Prestige Ltd.',
    'TV18BRDCST': 'TV18 Broadcast Ltd.',
    'TVSMOTOR': 'TVS Motor Company Ltd.',
    'TANLA': 'Tanla Platforms Ltd.',
    'TATACHEM': 'Tata Chemicals Ltd.',
    'TATACOFFEE': 'Tata Coffee Ltd.',
    'TATACOMM': 'Tata Communications Ltd.',
    'TCS': 'Tata Consultancy Services Ltd.',
    'TATACONSUM': 'Tata Consumer Products Ltd.',
    'TATAELXSI': 'Tata Elxsi Ltd.',
    'TATAINVEST': 'Tata Investment Corporation Ltd.',
    'TATAMTRDVR': 'Tata Motors Ltd DVR',
    'TATAMOTORS': 'Tata Motors Ltd.',
    'TATAPOWER': 'Tata Power Co. Ltd.',
    'TATASTLLP': 'Tata Steel Long Products Ltd.',
    'TATASTEEL': 'Tata Steel Ltd.',
    'TTML': 'Tata Teleservices (Maharashtra) Ltd.',
    'TEAMLEASE': 'Teamlease Services Ltd.',
    'TECHM': 'Tech Mahindra Ltd.',
    'NIACL': 'The New India Assurance Company Ltd.',
    'RAMCOCEM': 'The Ramco Cements Ltd.',
    'THERMAX': 'Thermax Ltd.',
    'THYROCARE': 'Thyrocare Technologies Ltd.',
    'TIMKEN': 'Timken India Ltd.',
    'TITAN': 'Titan Company Ltd.',
    'TORNTPHARM': 'Torrent Pharmaceuticals Ltd.',
    'TORNTPOWER': 'Torrent Power Ltd.',
    'TRENT': 'Trent Ltd.',
    'TRIDENT': 'Trident Ltd.',
    'TRITURBINE': 'Triveni Turbine Ltd.',
    'TIINDIA': 'Tube Investments of India Ltd.',
    'UCOBANK': 'UCO Bank',
    'UFLEX': 'UFLEX Ltd.',
    'UPL': 'UPL Ltd.',
    'UTIAMC': 'UTI Asset Management Company Ltd.',
    'ULTRACEMCO': 'UltraTech Cement Ltd.',
    'UNIONBANK': 'Union Bank of India',
    'UBL': 'United Breweries Ltd.',
    'MCDOWELL-N': 'United Spirits Ltd.',
    'VGUARD': 'V-Guard Industries Ltd.',
    'VMART': 'V-Mart Retail Ltd.',
    'VIPIND': 'V.I.P. Industries Ltd.',
    'VAIBHAVGBL': 'Vaibhav Global Ltd.',
    'VAKRANGEE': 'Vakrangee Ltd.',
    'VTL': 'Vardhman Textiles Ltd.',
    'VARROC': 'Varroc Engineering Ltd.',
    'VBL': 'Varun Beverages Ltd.',
    'VEDL': 'Vedanta Ltd.',
    'VENKEYS': "Venky's (India) Ltd.",
    'VIJAYA': 'Vijaya Diagnostic Centre Ltd.',
    'VINATIORGA': 'Vinati Organics Ltd.',
    'IDEA': 'Vodafone Idea Ltd.',
    'VOLTAS': 'Voltas Ltd.',
    'WELCORP': 'Welspun Corp Ltd.',
    'WELSPUNIND': 'Welspun India Ltd.',
    'WESTLIFE': 'Westlife Development Ltd.',
    'WHIRLPOOL': 'Whirlpool of India Ltd.',
    'WIPRO': 'Wipro Ltd.',
    'WOCKPHARMA': 'Wockhardt Ltd.',
    'YESBANK': 'Yes Bank Ltd.',
    'ZFCVINDIA': 'ZF Commercial Vehicle Control Systems India Ltd.',
    'ZEEL': 'Zee Entertainment Enterprises Ltd.',
    'ZENSARTECH': 'Zensar Technolgies Ltd.',
    'ZOMATO': 'Zomato Ltd.',
    'ZYDUSLIFE': 'Zydus Lifesciences Ltd.',
    'ZYDUSWELL': 'Zydus Wellness Ltd.',
    'ECLERX': 'eClerx Services Ltd.'}

